### ISSUE TITLE
Get to work on ARM

### ISSUE THREAD

**Issue by FLYBYME** [gliderlabs/herokuish#87]
What would it take to get this to work on ARM?

**Comment by michaelshobbs** [comment]
Which version of ARM should we support? (I have limited exposure to this architecture.)

NOTE on `GOARM` https://github.com/golang/go/wiki/GoArm

**Comment by josegonzalez** [comment]
[Scaleway](https://www.scaleway.com/) uses ARMv7.

**Comment by FLYBYME** [comment]
Yes Im looking at ARMv7 from scaleway. I dont think Ill have a problem compiling herokuish, but what about the buildpacks running on arm? Are they locked into an architecture?

**Comment by michaelshobbs** [comment]
In general, no, not that I am aware of.

**Comment by FLYBYME** [comment]
@michaelshobbs Ok thanks Ill give it a try today and see how it does.

**Comment by FLYBYME** [comment]
Sorry for been thick headed but how do you build this?

**Comment by FLYBYME** [comment]
Why would I get an error like this:

```
root@scw-36681c:~/herokuish# ./build/linux/herokuish
2015/12/14 19:34:05 exec: not started
```

I dont know much about go so Im kinda going error by error.

I built an image of `heroku/cedar:14` to work on arm. 

I run this: ` mkdir -p build/linux  && GOOS=linux  go build -ldflags "-X main.Version 0.3.5" -o build/linux/herokuish`

I dont really understand what Im going.

This is the output then I run make.

```
root@scw-36681c:~/herokuish# make
cat buildpacks/*/buildpack* | sed 'N;s/\n/ /' > include/buildpacks.txt
go-bindata include
mkdir -p build/linux  && GOOS=linux  go build -ldflags "-X main.Version 0.3.5" -o build/linux/herokuish
# _/root/herokuish
link: warning: option -X main.Version 0.3.5 may not work in future releases; use -X main.Version=0.3.5
docker build -f Dockerfile.dev -t herokuish:dev .
Sending build context to Docker daemon 3.972 MB
Step 1 : FROM mangoraft/armbuild-cedar14
 ---> f23d74b43c84
Step 2 : COPY ./build/linux/herokuish /bin/herokuish
 ---> 8dbe4e5ec95a
Removing intermediate container 40c711005394
Step 3 : RUN /bin/herokuish buildpack install   && ln -s /bin/herokuish /build  && ln -s /bin/herokuish /start  && ln -s /bin/herokuish /exec
 ---> Running in 513fb6caed4d
2015/12/14 19:37:44 exec: not started
The command '/bin/sh -c /bin/herokuish buildpack install        && ln -s /bin/herokuish /build  && ln -s /bin/herokuish /start && ln -s /bin/herokuish /exec' returned a non-zero code: 1
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 1
```

**Comment by michaelshobbs** [comment]
Ah! We assume `exec` is available on the system. Is this not true on ARM?

**Comment by FLYBYME** [comment]
`exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]` its available.

**Comment by FLYBYME** [comment]
Ran make again and got a new error.


```
root@scw-36681c:~/herokuish# make
cat buildpacks/*/buildpack* | sed 'N;s/\n/ /' > include/buildpacks.txt
go-bindata include
mkdir -p build/linux  && GOOS=linux  go build -ldflags "-X main.Version 0.3.5" -o build/linux/herokuish
# _/root/herokuish
link: warning: option -X main.Version 0.3.5 may not work in future releases; use -X main.Version=0.3.5
docker build -f Dockerfile.dev -t herokuish:dev .
Sending build context to Docker daemon 3.972 MB
Step 1 : FROM mangoraft/armbuild-cedar14
 ---> f23d74b43c84
Step 2 : COPY ./build/linux/herokuish /bin/herokuish
 ---> bcb3b0219cc4
Removing intermediate container beb89e99ec78
Step 3 : RUN /bin/herokuish buildpack install   && ln -s /bin/herokuish /build  && ln -s /bin/herokuish /start  && ln -s /bin/herokuish /exec
 ---> Running in 1defeb312551
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x8dcb0]

goroutine 8 [running]:
os.(*Process).signal(0x0, 0xb6e4f048, 0x109da270, 0x0, 0x0)
        /usr/lib/go/src/os/exec_unix.go:40 +0x24
os.(*Process).Signal(0x0, 0xb6e4f048, 0x109da270, 0x0, 0x0)
        /usr/lib/go/src/os/doc.go:51 +0x38
github.com/progrium/go-basher.(*Context).Run.func1(0x109d4280, 0x107a4000)
        /root/go/src/github.com/progrium/go-basher/basher.go:248 +0x78
created by github.com/progrium/go-basher.(*Context).Run
        /root/go/src/github.com/progrium/go-basher/basher.go:253 +0x4b0

goroutine 1 [runnable]:
fmt.(*pp).handleMethods(0x1056a090, 0x76, 0x0, 0x0)
        /usr/lib/go/src/fmt/print.go:693 +0x84
fmt.(*pp).printArg(0x1056a090, 0x173578, 0x10bfe020, 0x76, 0x0, 0x0)
        /usr/lib/go/src/fmt/print.go:806 +0x3d0
fmt.(*pp).doPrint(0x1056a090, 0x1052fe6c, 0x1, 0x1, 0x10500000)
        /usr/lib/go/src/fmt/print.go:1254 +0x270
fmt.Sprint(0x1052fe6c, 0x1, 0x1, 0x0, 0x0)
        /usr/lib/go/src/fmt/print.go:239 +0x58
log.Fatal(0x1052fe6c, 0x1, 0x1)
        /usr/lib/go/src/log/log.go:300 +0x2c
github.com/progrium/go-basher.Application(0x1050a740, 0x1052ff6c, 0x6, 0x6, 0x1cdcb8, 0x1050a701)
        /root/go/src/github.com/progrium/go-basher/basher.go:76 +0x714
main.main()
        /root/herokuish/herokuish.go:92 +0x184

goroutine 5 [syscall]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:22 +0x14
created by os/signal.init.1
        /usr/lib/go/src/os/signal/signal_unix.go:28 +0x30

goroutine 33 [select, locked to thread]:
runtime.gopark(0x1cdea4, 0x107a3f8c, 0x192df8, 0x6, 0x43518, 0x2)
        /usr/lib/go/src/runtime/proc.go:185 +0x148
runtime.selectgoImpl(0x107a3f8c, 0x0, 0xc)
        /usr/lib/go/src/runtime/select.go:392 +0x14d4
runtime.selectgo(0x107a3f8c)
        /usr/lib/go/src/runtime/select.go:212 +0x10
runtime.ensureSigM.func1()
        /usr/lib/go/src/runtime/signal1_unix.go:227 +0x428
runtime.goexit()
        /usr/lib/go/src/runtime/asm_arm.s:1036 +0x4
The command '/bin/sh -c /bin/herokuish buildpack install        && ln -s /bin/herokuish /build  && ln -s /bin/herokuish /start && ln -s /bin/herokuish /exec' returned a non-zero code: 2
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 1

```

**Comment by michaelshobbs** [comment]
Is the problem we're copying the linux built version and trying to run that? Are we sure that target is built to run on ARM?

**Comment by michaelshobbs** [comment]
Maybe there's some issue with running progrium/go-basher on ARM?

**Comment by FLYBYME** [comment]
I have recompiled go and going to go give it another.. go.

**Comment by FLYBYME** [comment]
I really dont have the knowledge need to get this to work.

```
root@scw-36681c:~/herokuish# GOOS=linux  go build -ldflags "-X main.Version 0.3.5" -o build/linux/herokuish
# github.com/progrium/go-basher
../go/src/github.com/progrium/go-basher/bash_linux.go:6: import /root/go/pkg/linux_arm/bytes.a: object is [linux arm go1.4.1 X:precisestack] expected [linux arm go1.5.1 X:none]
```

Im going to start playing around with an older version `0.2.0` and see if that might work.

@michaelshobbs If it might help getting this done I can set you up with an instance from scaleway, maybe you could do a better job then me.

**Comment by michaelshobbs** [comment]
haha go...go...go! :smile:

I'd love to help out here. However, I won't have time to work on this until next week or the week after. Feel free to set me up with an account and keep banging away as much as you have time to do. I'm glad to pick up wherever you end up running out of time.

Thanks for jumping in on this!

**Comment by FLYBYME** [comment]
im on the IRC and it seems that the problem is with https://github.com/progrium/go-basher/blob/3321ddc36cac3290fefc851285d40348b1f69b5b/basher.go#L254

I think it is missing error checking.

**Comment by FLYBYME** [comment]
So i spent all day trying to fix this problem. @kron4eg pointed me in the right direct. The problem is that bash is hard coded into go-basher. 

I fixed the with this "cp /bin/bash ~/.basher/bash"

Thank you @kron4eg

**Comment by josegonzalez** [comment]
@FLYBYME have you made any progress on this front recently?

**Comment by FLYBYME** [comment]
Yes I got it working but the buildpacks mostly wont work. They are all x86/arm64

**Comment by josegonzalez** [comment]
Can we rebuild buildpacks?

**Comment by FLYBYME** [comment]
Im going to do what I can and add them here https://github.com/raft-buildpacks-arm

**Comment by mainto** [comment]
I compiled dokku, herokuish, heroku-buildpack-nodejs and I tested on my Raspberry Pi 2 (4.1.12-hypriotos-v7+)

```
HypriotOS: pi@black-pearl in ~/dokku/mainto
$ uname -a
Linux black-pearl 4.1.12-hypriotos-v7+ #2 SMP PREEMPT Tue Nov 3 19:44:55 UTC 2015 armv7l GNU/Linux
HypriotOS: pi@black-pearl in ~/dokku/mainto
$ docker -v
Docker version 1.10.1, build 9e83765
HypriotOS: pi@black-pearl in ~/dokku/mainto
$ sudo dokku version
v0.4.14-26-ga16fc56
```

when I push a node app to my pi dokku, it takes a while to build but it works.
still it show some error message but app is deployed.
I believe that it is still needed lots of test and it is just first step for me.

I paste push output for node-js-getting-started from heroku
and url is [http://test.krpi.dko.me](url)

```
$ git push krpi master
Counting objects: 433, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (336/336), done.
Writing objects: 100% (433/433), 222.26 KiB | 0 bytes/s, done.
Total 433 (delta 64), reused 433 (delta 64)
-----> Cleaning up...
-----> Building test from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  0.12.7
       engines.npm (package.json):   unspecified (use default)
       
       Downloading and installing node 0.12.7...
       Using default npm version: 2.11.3
       
-----> Restoring cache
       Skipping cache restore (new runtime signature)
       
-----> Building dependencies
       Pruning any extraneous modules
       Installing node modules (package.json)
       ejs@2.3.3 node_modules/ejs
       
       express@4.13.3 node_modules/express
       ├── escape-html@1.0.2
       ├── merge-descriptors@1.0.0
       ├── array-flatten@1.1.1
       ├── cookie@0.1.3
       ├── utils-merge@1.0.0
       ├── cookie-signature@1.0.6
       ├── fresh@0.3.0
       ├── methods@1.1.2
       ├── range-parser@1.0.3
       ├── vary@1.0.1
       ├── path-to-regexp@0.1.7
       ├── parseurl@1.3.1
       ├── content-type@1.0.1
       ├── etag@1.7.0
       ├── content-disposition@0.5.0
       ├── depd@1.0.1
       ├── qs@4.0.0
       ├── on-finished@2.3.0 (ee-first@1.1.1)
       ├── finalhandler@0.4.0 (unpipe@1.0.0)
       ├── debug@2.2.0 (ms@0.7.1)
       ├── proxy-addr@1.0.10 (forwarded@0.1.0, ipaddr.js@1.0.5)
       ├── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)
       ├── serve-static@1.10.2 (escape-html@1.0.3, send@0.13.1)
       ├── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.10)
       └── type-is@1.6.11 (media-typer@0.3.0, mime-types@2.1.10)
       
-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)
       
-----> Build succeeded!
       ├── ejs@2.3.3
       └── express@4.13.3
       
-----> Discovering process types
       Procfile declares types -> web
-----> Releasing test (dokku/test:latest)...
-----> Deploying test (dokku/test:latest)...
-----> Attempting to run scripts.dokku.predeploy from app.json (if defined)
remote: Traceback (most recent call last):
remote:   File "<string>", line 1, in <module>
remote: KeyError: 'scripts'
-----> App Procfile file found (/home/dokku/test/DOKKU_PROCFILE)
-----> DOKKU_SCALE file not found in app image. Generating one based on Procfile...
-----> New DOKKU_SCALE file generated
=====> web=1
-----> Running pre-flight checks
       For more efficient zero downtime deployments, create a file CHECKS.
       See http://dokku.viewdocs.io/dokku/checks-examples.md for examples
       CHECKS file not found in container: Running simple container check...
-----> Waiting for 10 seconds ...
-----> Default container check successful!
=====> test container output:
       Node app is running on port 5000
=====> end test container output
-----> Running post-deploy
-----> Attempting to run scripts.dokku.postdeploy from app.json (if defined)
remote: Traceback (most recent call last):
remote:   File "<string>", line 1, in <module>
remote: KeyError: 'scripts'
=====> renaming container (db2c7bdf9d88) gloomy_spence to test.web.1
-----> Creating new /home/dokku/test/VHOST...
-----> Setting config vars
       DOKKU_NGINX_PORT: 80
-----> Configuring test.krpi.dko.me...(using built-in template)
-----> Creating http nginx.conf
-----> Running nginx-pre-reload
       Reloading nginx
-----> Setting config vars
       DOKKU_APP_RESTORE: 1
=====> Application deployed:
       http://test.krpi.dko.me

To dokku@krpi.dko.me:test
 * [new branch]      master -> master
```

**Comment by josegonzalez** [comment]
@michaelshobbs we probably fixed that `scripts` key bug in master, right? If so, looks like we might be in a good position to *somehow* do this. Maybe the scaleway folks have a way to do CI or something? Could be an easy way to add dokku support to arm if we can prove that herokuish and all buildpacks will build...

**Comment by michaelshobbs** [comment]
yeah that's fixed. however, the issue is more around buildpack support on ARM. not sure that's in the scope of heroku support.... **shrug**

**Comment by josegonzalez** [comment]
Ah right, they force-download certain compiled binaries.

**Comment by Shchvova** [comment]
Sorry for commenting an old issue, but server ARM crawled its way into main stream since the original issue was closed. Pretty much all cloud providers now have ARM offerings.
For example, you can get 16 core 50+ gb RAM machine for oracle cloud free tier. Any chances on making herokuish available for those types of machines? This is especially relevant today, with heroku hiking up prices and getting rid of free tier.

Cheers!

**Comment by josegonzalez** [comment]
Herokuish itself should work fine on ARM.

The problem is that many of those buildpacks either download pre-compiled things for AMD64 or only target AMD64. Some might work out of the box (golang, maybe java) but others (python, ruby, php) would probably need work in order to target ARM. At that point, I'm basically maintaining the buildpack codebases and files, and I already don't have enough time for everything in the Dokku world.

If you're interested in support for a particular language and would like to sponsor my time, [here](https://github.com/dokku/.github/blob/master/SPONSORING.md) is a doc that covers how sponsorship works. Otherwise, Dokku also supports Cloud Native Buildpacks (via CNB/pack) and you could write your own buildpack that works for ARM.
